holder_power: 0.8
target_power: 0.2
force_pull_power: 0.1
max_distance: 10
force_teleport_distance: 20
lead_after_death: false
lead_only_player: false
particle_mode: false
particle_type: "CRIT"